mysite/accounts/urls.py
from django.conf.urls import url
from .import views
from django.contrib.auth.views import login,logout


urlpatterns = [

    url(r'^login/$',login,{'template_name':'accounts/login.html'}),
    url(r'^logout/$',logout,{'template_name':'accounts/logout.html'}),
    url(r'^register/$',views.register,name='register'),
    url(r'^profile/$',views.view_profile,name='view_profile'),
    url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password')

]

mysite/chat/urls.py
# chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

mysite/home/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
   # url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/like/(?P<pk>\d+)/', views.like, name = 'like'),
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from mysite import views

urlpatterns = [

    url(r'^$',views.login_redirect,name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^home/',include('home.urls',namespace='home')),
    url(r'^chat/',include('chat.urls',namespace='chat')),]

mysite/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100,default='')
    city=models.CharField(max_length=100,default='')
    website=models.URLField(default='')
    phone=models.IntegerField(default=0)
def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile=UserProfile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile,sender=User)

mysite/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields =(
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )
    def save(self,commit=True):
        user=super(RegistrationForm,self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model=User
        fields=('email','first_name','last_name','password')

mysite/accounts/views.py
from django.shortcuts import render,redirect
from accounts.forms import (
    RegistrationForm,
    EditProfileForm
   )
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash




def register(request):
    if request.method =='POST':
        form=RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts')
    else:
        form=RegistrationForm()
        args={'form':form}
        return render(request,'accounts/reg_form.html',args)

def view_profile(request):
    args ={'user': request.user}
    return render(request,'accounts/profile.html',args)

def edit_profile(request):
    if request.method =='POST':
        form=EditProfileForm(request.POST,instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('account/profile')
    else:
        form=EditProfileForm(instance=request.user)
        args={'form':form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method =='POST':
        form=PasswordChangeForm(data=request.POST,user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('account/profile')
        else:
            return redirect('accounts/change-password')
    else:
        form=PasswordChangeForm(user=request.user)
        args={'form':form}
        return render(request, 'accounts/change_password.html', args)

mysite/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% block head %}
<title>Bootstrap Example</title>
    {% endblock %}
</head>
<body>
 <div class="container">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">Blog SignUp</a>
    </div>
     {% if user.is_authenticated %}
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'home:post_list' %}">Home</a></li>
      <li class="active"><a href="/accounts/logout">Logout</a></li>
      <li class="active"><a href="/accounts/profile">Profile</a></li>
      <li class="active"><a href="/accounts/change-password">Change Password</a></li>
      <li class="active"><a href="/accounts/profile/edit">Edit Profile</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/accounts/register"><span class="glyphicon glyphicon-user"></span>Register</a></li>
    </ul>
      {% else %}
     <ul class="nav navbar-nav">
       <!--  <li class="active"><a href="{% url 'home:post_list' %} ">Home</a></li>-->
       <li class="active"><a href="/accounts/login">Login</a></li>
      <!--<li class="active"><a href="/accounts/logout">Logout</a></li>-->
      <!--<li class="active"><a href="/accounts/profile">Profile</a></li>-->
      <!--<li class="active"><a href="/accounts/change-password">Change Password</a></li>-->
      <!--<li class="active"><a href="/accounts/profile/edit">Edit Profile</a></li>-->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/accounts/register"><span class="glyphicon glyphicon-user"></span>Register</a></li>
    </ul>
     {% endif %}
  </div>
</nav>
      </div>
           {% block body %}
{% endblock %}
</body>
</html>