mysite/chat/urls.py
# chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

mysite/home/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
   # url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/like/(?P<pk>\d+)/', views.like, name = 'like'),
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from mysite import views

urlpatterns = [

    url(r'^$',views.login_redirect,name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^home/',include('home.urls',namespace='home')),
    url(r'^chat/',include('chat.urls',namespace='chat')),]

mysite/home/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('home.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text
class Addlikes(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField(default='xxxxx')
    liketime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
      return self.post

mysite/home/forms.py
from django import forms

from .models import Post,Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

mysite/home/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.utils import timezone
from .models import Post,Comment
from .forms import PostForm,CommentForm
from django.contrib.auth.decorators import login_required

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'home/home.html', {'posts': posts})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('home:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'home/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('home:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'home/post_edit.html', {'form': form})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'home/post_detail.html', {'post': post})


def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('home:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'home/add_comment_to_post.html', {'form': form})
@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('home:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('home:post_detail', pk=comment.post.pk)
#def post_publish(request, pk):
 #   post = get_object_or_404(Post, pk=pk)
  #  post.publish()
   # return redirect('home:post_detail', pk=pk)
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('home:post_list')

def like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    likes = Addlikes.objects.all()
    print (post) 
    if request.method == "GET":
        p = Post.objects.get(pk=pk)
        p.likes+=1
        p.save()
        b = Addlikes(post=post, user=request.user)
        b.save()
    return HttpResponseRedirect('/home/post/'+pk)

mysite/home/templates/home/add_comment_to_post.html
{% extends 'base1.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

mysite/home/templates/home/home.html
{% extends 'base1.html' %}

{%  block content %}
	{% for post in posts %}
		<div class="post">
			<div class="date">
				<p>published: {{ post.published_date}}</p>
			</div>
			<h1><a href="{% url 'home:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
			<p>{{ post.text|linebreaks }}</p>

		<a href="{% url 'home:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
                
		</div>
			{% endfor %}
{%  endblock %}

mysite/home/templates/home/post_detail.html
{% extends 'base1.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
    <div class="date">
        {{ post.published_date }}
    </div>
{% endif %}
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'home:post_edit' pk=post.pk %}">
            <span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{% url 'home:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
<u><h1>{{ post.title }}</h1></u>
        <h3>{{ post.post }}</h3>
        <u><h2>{{ post.user }}</h2></u>
         <u><h2>{{ post.likes }}</h2></u>
        <br><br>
<button class="btn btn-success"><a href="{% url 'home:like' post.id %}">LIKE</a></button>
<hr>
<a class="btn btn-default" href="{% url 'home:add_comment_to_post' pk=post.pk %}">Add comment</a>
{% for comment in post.comments.all %}
 {% if user.is_authenticated or comment.approved_comment %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}
            {% if not comment.approved_comment %}

                <a class="btn btn-default" href="{% url 'home:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-default" href="{% url 'home:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
            {% endif %}
        </div>

        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>{% endif %}
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
{% endblock %}

mysite/home/templates/home/post_edit.html
{% extends 'base1.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}